# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stuart/stulibcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stuart/stulibcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/stuart/stulibcpp/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stuart/stulibcpp/CMakeFiles /home/stuart/stulibcpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stuart/stulibcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stucpp

# Build rule for target.
stucpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stucpp
.PHONY : stucpp

# fast build rule for target.
stucpp/fast:
	$(MAKE) -f CMakeFiles/stucpp.dir/build.make CMakeFiles/stucpp.dir/build
.PHONY : stucpp/fast

#=============================================================================
# Target rules for targets named basic

# Build rule for target.
basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic
.PHONY : basic

# fast build rule for target.
basic/fast:
	$(MAKE) -f CMakeFiles/basic.dir/build.make CMakeFiles/basic.dir/build
.PHONY : basic/fast

src/ApiClass.o: src/ApiClass.cpp.o

.PHONY : src/ApiClass.o

# target to build an object file
src/ApiClass.cpp.o:
	$(MAKE) -f CMakeFiles/stucpp.dir/build.make CMakeFiles/stucpp.dir/src/ApiClass.cpp.o
.PHONY : src/ApiClass.cpp.o

src/ApiClass.i: src/ApiClass.cpp.i

.PHONY : src/ApiClass.i

# target to preprocess a source file
src/ApiClass.cpp.i:
	$(MAKE) -f CMakeFiles/stucpp.dir/build.make CMakeFiles/stucpp.dir/src/ApiClass.cpp.i
.PHONY : src/ApiClass.cpp.i

src/ApiClass.s: src/ApiClass.cpp.s

.PHONY : src/ApiClass.s

# target to generate assembly for a file
src/ApiClass.cpp.s:
	$(MAKE) -f CMakeFiles/stucpp.dir/build.make CMakeFiles/stucpp.dir/src/ApiClass.cpp.s
.PHONY : src/ApiClass.cpp.s

src/CApi.o: src/CApi.cpp.o

.PHONY : src/CApi.o

# target to build an object file
src/CApi.cpp.o:
	$(MAKE) -f CMakeFiles/stucpp.dir/build.make CMakeFiles/stucpp.dir/src/CApi.cpp.o
.PHONY : src/CApi.cpp.o

src/CApi.i: src/CApi.cpp.i

.PHONY : src/CApi.i

# target to preprocess a source file
src/CApi.cpp.i:
	$(MAKE) -f CMakeFiles/stucpp.dir/build.make CMakeFiles/stucpp.dir/src/CApi.cpp.i
.PHONY : src/CApi.cpp.i

src/CApi.s: src/CApi.cpp.s

.PHONY : src/CApi.s

# target to generate assembly for a file
src/CApi.cpp.s:
	$(MAKE) -f CMakeFiles/stucpp.dir/build.make CMakeFiles/stucpp.dir/src/CApi.cpp.s
.PHONY : src/CApi.cpp.s

test/basic.o: test/basic.cpp.o

.PHONY : test/basic.o

# target to build an object file
test/basic.cpp.o:
	$(MAKE) -f CMakeFiles/basic.dir/build.make CMakeFiles/basic.dir/test/basic.cpp.o
.PHONY : test/basic.cpp.o

test/basic.i: test/basic.cpp.i

.PHONY : test/basic.i

# target to preprocess a source file
test/basic.cpp.i:
	$(MAKE) -f CMakeFiles/basic.dir/build.make CMakeFiles/basic.dir/test/basic.cpp.i
.PHONY : test/basic.cpp.i

test/basic.s: test/basic.cpp.s

.PHONY : test/basic.s

# target to generate assembly for a file
test/basic.cpp.s:
	$(MAKE) -f CMakeFiles/basic.dir/build.make CMakeFiles/basic.dir/test/basic.cpp.s
.PHONY : test/basic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... stucpp"
	@echo "... edit_cache"
	@echo "... basic"
	@echo "... src/ApiClass.o"
	@echo "... src/ApiClass.i"
	@echo "... src/ApiClass.s"
	@echo "... src/CApi.o"
	@echo "... src/CApi.i"
	@echo "... src/CApi.s"
	@echo "... test/basic.o"
	@echo "... test/basic.i"
	@echo "... test/basic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

